#!/bin/bash

REPODIR=$(cd $(dirname $0); pwd)

ARROW_BUILD_DIR=${REPODIR}/cpp/build

mkdir -p ${ARROW_BUILD_DIR}
cd  ${ARROW_BUILD_DIR}

cmake .. \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_FLAGS="-std=c++11" \
  -DCMAKE_INSTALL_LIBDIR="lib" \
  -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
  -DARROW_WITH_LZ4=ON \
  -DARROW_WITH_ZSTD=ON \
  -DARROW_WITH_SNAPPY=ON \
  -DARROW_WITH_BROTLI=OFF \
  -DARROW_BUILD_STATIC=ON \
  -DARROW_BUILD_SHARED=ON \
  -DARROW_BOOST_USE_SHARED=OFF \
  -DARROW_BUILD_TESTS=OFF \
  -DARROW_TEST_LINKAGE=OFF \
  -DARROW_TEST_MEMCHECK=OFF \
  -DARROW_BUILD_BENCHMARKS=OFF \
  -DARROW_IPC=ON \
  -DARROW_FLIGHT=OFF \
  -DARROW_COMPUTE=ON \
  -DARROW_CUDA=ON \
  -DARROW_ORC=ON \
  -DARROW_PARQUET=ON \
  -DARROW_PLASMA=ON \
  -DARROW_JEMALLOC=OFF \
  -DARROW_BOOST_VENDORED=OFF \
  -DARROW_PYTHON=ON \
  -DARROW_USE_GLOG=OFF \
  -DARROW_DATASET=ON \
  -DARROW_BUILD_UTILITIES=OFF \
  -DARROW_HDFS=OFF \
  -DCMAKE_VERBOSE_MAKEFILE=ON \
  -DTHRIFT_STATIC_LIB=${CONDA_PREFIX}/lib/libthrift.a \
  -DTHRIFT_INCLUDE_DIR=${CONDA_PREFIX}/include \
  ..

make -j${PARALLEL_LEVEL}
make install

